"use client";

import { useState, useRef, DragEvent } from "react";
import styles from "./page.module.css";
import { FaRegFileImage } from "react-icons/fa";

interface Result {
  label: string;
  confidence: string;
}

export default function ArtDetector() {
  const [result, setResult] = useState<Result | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isDragOver, setIsDragOver] = useState(false);
  const [preview, setPreview] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFile = (file: File) => {
    const url = URL.createObjectURL(file);
    setPreview(url);
    analyse(file);
  };

  const analyse = async (file: File) => {
    setLoading(true);
    setResult(null);
    setError(null);

    const formData = new FormData();
    formData.append("image", file);

    try {
      const res  = await fetch("/api/predict", { method: "POST", body: formData });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setResult({
        label:      data.label,
        confidence: `${(data.confidence * 100).toFixed(2)}% confidence`,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const onDragOver  = (e: DragEvent) => { e.preventDefault(); setIsDragOver(true); };
  const onDragLeave = () => setIsDragOver(false);
  const onDrop      = (e: DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) handleFile(file);
  };

  return (
    <div className={styles.page}>
      <h1 className={styles.heading}>AI Art Detector</h1>
      <p className={styles.subheading}>Upload an image to find out if it was made by a human or generated by AI.</p>

      <div
        className={`${styles.dropzone} ${isDragOver ? styles.dropzoneActive : ""}`}
        onClick={() => fileInputRef.current?.click()}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
        onDrop={onDrop}
      >
        {preview ? (
          <img src={preview} alt="Uploaded preview" className={styles.preview} />
        ) : (
          <div className={styles.dropzonePrompt}>
            <FaRegFileImage size={32}/>
            <strong>Drop an image here</strong>
            <p>or click to browse</p>
          </div>
        )}
      </div>

      <input
        ref={fileInputRef}
        type="file"
        accept="image/*"
        style={{ display: "none" }}
        onChange={(e) => { if (e.target.files?.[0]) handleFile(e.target.files[0]); }}
      />

      {loading && <p className={styles.loading}>Analysing…</p>}

      {result && (
        <div className={styles.resultBox}>
          <p className={styles.resultLabel}>{result.label}</p>
          <p className={styles.resultConfidence}>{result.confidence}</p>
          <p className={styles.resultHint}>Click the image to analyse another</p>
        </div>
      )}

      {error && <div className={styles.error}>Error: {error}</div>}
    </div>
  );
}